import * as Icons from '@fortawesome/free-solid-svg-icons'

const ICONS = {
    ASTERISK: { NAME: 'faAsterisk', ICON: Icons.faAsterisk },
    ADDRESS_CARD: { NAME: 'faAddressCard', ICON: Icons.faAddressCard },
    BARS: { NAME: 'faBars', ICON: Icons.faBars },
    APPLE: { NAME: 'faAppleAlt', ICON: Icons.faAppleAlt },
    ARCHIVE: { NAME: 'faArchive', ICON: Icons.faArchive },
    AT: { NAME: 'faAt', ICON: Icons.faAt },
    ATOM: { NAME: 'faAtom', ICON: Icons.faAtom },
    BEER: { NAME: 'faBeer', ICON: Icons.faBeer },
    BICYCLE: { NAME: 'faBicycle', ICON: Icons.faBicycle },
    BOLT: { NAME: 'faBolt', ICON: Icons.faBolt },
    BOOK: { NAME: 'faBook', ICON: Icons.faBook },
    BOOKMARK: { NAME: 'faBookmark', ICON: Icons.faBookmark },
    BOXES: { NAME: 'faBoxes', ICON: Icons.faBoxes },
    BUILDING: { NAME: 'faBuilding', ICON: Icons.faBuilding },
    BURN: { NAME: 'faBurn', ICON: Icons.faBurn },
    CALENDAR: { NAME: 'faCalendar', ICON: Icons.faCalendar },
    CAMERA: { NAME: 'faCamera', ICON: Icons.faCamera },
    PIE: { NAME: 'faChartPie', ICON: Icons.faChartPie },
    CLIPBOARD: { NAME: 'faClipboardList', ICON: Icons.faClipboardList },
    CLOCK: { NAME: 'faClock', ICON: Icons.faClock },
    CLOUD: { NAME: 'faCloud', ICON: Icons.faCloud },
    COFFEE: { NAME: 'faCoffee', ICON: Icons.faCoffee },
    COG: { NAME: 'faCog', ICON: Icons.faCog },
    COMMENT: { NAME: 'faComment', ICON: Icons.faComment },
    COMPASS: { NAME: 'faCompass', ICON: Icons.faCompass },
    CREDIT: { NAME: 'faCreditCard', ICON: Icons.faCreditCard },
    CUBE: { NAME: 'faCube', ICON: Icons.faCube },
    DESKTOP: { NAME: 'faDesktop', ICON: Icons.faDesktop },
    DICE: { NAME: 'faDice', ICON: Icons.faDice },
    DOLLAR: { NAME: 'faDollarSign', ICON: Icons.faDollarSign },
    ENVELOPE: { NAME: 'faEnvelope', ICON: Icons.faEnvelope },
    EXCLAMATION: { NAME: 'faExclamation', ICON: Icons.faExclamation },
    EYE: { NAME: 'faEye', ICON: Icons.faEye },
    FILE: { NAME: 'faFile', ICON: Icons.faFile },
    FIST: { NAME: 'faFistRaised', ICON: Icons.faFistRaised },
    FLAG: { NAME: 'faFlag', ICON: Icons.faFlag },
    FLASK: { NAME: 'faFlask', ICON: Icons.faFlask },
    GAMEPAD: { NAME: 'faGamepad', ICON: Icons.faGamepad },
    GLASSES: { NAME: 'faGlasses', ICON: Icons.faGlasses },
    GLOBE: { NAME: 'faGlobe', ICON: Icons.faGlobe },
    GRIN: { NAME: 'faGrin', ICON: Icons.faGrin },
    GUITAR: { NAME: 'faGuitar', ICON: Icons.faGuitar },
    HAMMER: { NAME: 'faHammer', ICON: Icons.faHammer },
    HANDS: { NAME: 'faHands', ICON: Icons.faHands },
    HEART: { NAME: 'faHeart', ICON: Icons.faHeart },
    IMAGE: { NAME: 'faImage', ICON: Icons.faImage },
    KEYBOARD: { NAME: 'faKeyboard', ICON: Icons.faKeyboard },
    LIGHTBULB: { NAME: 'faLightbulb', ICON: Icons.faLightbulb },
}

export default ICONS