import * as Icons from '@fortawesome/free-solid-svg-icons'

const ICONS = {
    ASTERISK: { NAME: 'faAsterisk', ICON: Icons.faAsterisk },
    ADDRESS_CARD: { NAME: 'faAddressCard', ICON: Icons.faAddressCard },
    BARS: { NAME: 'faBars', ICON: Icons.faBars },
    APPLE: { NAME: 'faAppleAlt', ICON: Icons.faAppleAlt },
    ARCHIVE: { NAME: 'faArchive', ICON: Icons.faArchive },
    AT: { NAME: 'faAt', ICON: Icons.faAt },
    ATOM: { NAME: 'faAtom', ICON: Icons.faAtom },
    BICYCLE: { NAME: 'faBicycle', ICON: Icons.faBicycle },
    BOLT: { NAME: 'faBolt', ICON: Icons.faBolt },
    BOOK: { NAME: 'faBook', ICON: Icons.faBook },
    BOOKMARK: { NAME: 'faBookmark', ICON: Icons.faBookmark },
    BOXES: { NAME: 'faBoxes', ICON: Icons.faBoxes },
    BUILDING: { NAME: 'faBuilding', ICON: Icons.faBuilding },
    CALENDAR: { NAME: 'faCalendar', ICON: Icons.faCalendar },
    CAMERA: { NAME: 'faCamera', ICON: Icons.faCamera },
    PIE: { NAME: 'faChartPie', ICON: Icons.faChartPie },
    CLIPBOARD: { NAME: 'faClipboardList', ICON: Icons.faClipboardList },
    CLOUD: { NAME: 'faCloud', ICON: Icons.faCloud },
    COFFEE: { NAME: 'faCoffee', ICON: Icons.faCoffee },
    COG: { NAME: 'faCog', ICON: Icons.faCog },
    COMMENT: { NAME: 'faComment', ICON: Icons.faComment },
    COMPASS: { NAME: 'faCompass', ICON: Icons.faCompass },
    CREDIT: { NAME: 'faCreditCard', ICON: Icons.faCreditCard },
    DESKTOP: { NAME: 'faDesktop', ICON: Icons.faDesktop },
    DOLLAR: { NAME: 'faDollarSign', ICON: Icons.faDollarSign },
    ENVELOPE: { NAME: 'faEnvelope', ICON: Icons.faEnvelope },
    EYE: { NAME: 'faEye', ICON: Icons.faEye },
    FILE: { NAME: 'faFile', ICON: Icons.faFile },
    FLAG: { NAME: 'faFlag', ICON: Icons.faFlag },
    FLASK: { NAME: 'faFlask', ICON: Icons.faFlask },
    GAMEPAD: { NAME: 'faGamepad', ICON: Icons.faGamepad },
    GLASSES: { NAME: 'faGlasses', ICON: Icons.faGlasses },
    GLOBE: { NAME: 'faGlobe', ICON: Icons.faGlobe },
    GRIN: { NAME: 'faGrin', ICON: Icons.faGrin },
    HANDS: { NAME: 'faHands', ICON: Icons.faHands },
    HEART: { NAME: 'faHeart', ICON: Icons.faHeart },
    IMAGE: { NAME: 'faImage', ICON: Icons.faImage },
    KEYBOARD: { NAME: 'faKeyboard', ICON: Icons.faKeyboard },
    LIGHTBULB: { NAME: 'faLightbulb', ICON: Icons.faLightbulb },
    TSHIRT: { NAME: 'faTshirt', ICON: Icons.faTshirt },
    DICE: { NAME: 'faDice', ICON: Icons.faDice },
    FAN: { NAME: 'faFan', ICON: Icons.faFan },
    FIRE: { NAME: 'faFire', ICON: Icons.faFire },
    GEM: { NAME: 'faGem', ICON: Icons.faGem },
    GHOST: { NAME: 'faGhost', ICON: Icons.faGhost },
    JEDI: { NAME: 'faJedi', ICON: Icons.faJedi },
    SHIELD: { NAME: 'faShieldAlt', ICON: Icons.faShieldAlt },
    SKULL: { NAME: 'faSkull', ICON: Icons.faSkull },
    YINYANG: { NAME: 'faYinYang', ICON: Icons.faYinYang },
    VIDEO: { NAME: 'faVideo', ICON: Icons.faVideo },
    VIRUS: { NAME: 'faVirus', ICON: Icons.faVirus },
    VENUS: { NAME: 'faVenus', ICON: Icons.faVenus },
    MARS: { NAME: 'faMars', ICON: Icons.faMars },
    VENUS_MARS: { NAME: 'faVenusMars', ICON: Icons.faVenusMars },
    TRANS: { NAME: 'faTransgenderAlt', ICON: Icons.faTransgenderAlt },
    TOOLS: { NAME: 'faTools', ICON: Icons.faTools },
    TROPHY: { NAME: 'faTrophy', ICON: Icons.faTrophy },
    SHOPPING: { NAME: 'faShoppingBag', ICON: Icons.faShoppingBag },
    POOP: { NAME: 'faPoop', ICON: Icons.faPoop },
    SAVE: { NAME: 'faSave', ICON: Icons.faSave },
}

export default ICONS